FROM python:3.11-slim

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

COPY requirements_worker.txt ./
RUN pip install --no-cache-dir -r requirements_worker.txt

COPY . /usr/src/app

CMD ["arq", "netdrift.worker.config.WorkerSettings"]
