from enum import Enum


class APIExceptionCodes(int, Enum):
    RESERVED = 0

    # 1 - 99 for Generic errors.
    XML_PARSER_ERROR = 1
    NOT_IMPLEMENTED_ERROR = 2

    # 100 - 149 for AuthProvider errors.
    AUTH_PROVIDER_LOGIC_ERROR = 100

    # 500 - 599 for all *IntentConfig objects.
    INTENT_CONFIG_API_LOCK = 500
    INTENT_CONFIG_HOSTNAME_LOCK = 501

    # 600 - 699 for FullIntentConfig objects.
    FULL_INTENT_CONFIG_NOT_FOUND = 600
    FULL_INTENT_CONFIG_ALREADY_EXIST = 601
    FULL_INTENT_CONFIG_UPDATE_FAILED = 602

    # 700 - 799 for PartialIntentConfig objects.
    PARTIAL_INTENT_CONFIG_NOT_FOUND = 700
    PARTIAL_INTENT_CONFIG_ALREADY_EXIST = 701
    PARTIAL_INTENT_CONFIG_UPDATE_FAILED = 702
    PARTIAL_INTENT_CONFIG_FILTER_ALREADY_EXIST = 703

    # 800 - 899 for IntentGroup objects.
    INTENT_GROUP_NOT_FOUND = 800
    INTENT_GROUP_ALREADY_EXIST = 801
    INTENT_GROUP_UPDATE_FAILED = 802
    INTENT_GROUP_HOSTNAME_MANAGED = 803
    INTENT_GROUP_HOSTNAME_MISMATCH = 804
    INTENT_GROUP_POTENTIAL_RECURSION = 805
    INTENT_GROUP_DUPLICATION = 806
